fasttext_model = 'traditional_ml/pretrained_fasttext/vnlaw_ft.bin'
train_data_path = 'traditional_ml/feature_data/train_data_general.npy'
test_data_path = 'traditional_ml/feature_data/test_data_general.npy'
train_examples_path = 'traditional_ml/raw_data/train_examples.pkl'
test_examples_path = 'traditional_ml/raw_data/test_examples.pkl'
evaluation_output = 'traditional_ml/eval.csv'
